spring:
  datasource:
    url: ${spring.datasource.dev.url}
    username: ${spring.datasource.dev.username}
    password: ${spring.datasource.dev.password}
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858